### PR TITLE
fix(Accordion): Use empty SelectableContext to prevent dropdown from closing accordion

### LINKED ISSUE #4176: onClick stopPropagation() ignored on Dropdown, DropdownButton
Hi all, I'm new to React and react-bootstrap, so bear with me.  I'm building a form that is sectioned off by Accordion components.  Within an Accordion, I have a Card with a body, and within that body I have a DropdownButton.  When I select a DropdownButton value, the entire Accordion section collapses.  This can be reproduced on the following simple example:

```
import React from 'react'
import {Accordion, Dropdown, Card} from 'react-bootstrap'

const Test = props => {
    return (
        <Accordion defaultActiveKey="0">
            <Accordion.Toggle as={Card.Header} eventKey="0"><strong>Transaction Details</strong></Accordion.Toggle>
            <Accordion.Collapse eventKey="0">
                <div >
                    <Card body>
                    <Dropdown >
                        <Dropdown.Toggle variant="success" id="dropdown-basic">
                            Dropdown Button
                        </Dropdown.Toggle>

                        <Dropdown.Menu  >
                            <Dropdown.Item href="#/action-1">Action</Dropdown.Item>
                            <Dropdown.Item href="#/action-2">Another action</Dropdown.Item>
                            <Dropdown.Item href="#/action-3">Something else</Dropdown.Item>
                        </Dropdown.Menu>
                    </Dropdown>
                    </Card>
                </div>
            </Accordion.Collapse>
        </Accordion>
    )
}

export default Test
```

I believe this has to do with event bubbling, and that my Accordion component's onClick event is also firing.  However, I've tried to set my `stopPropagation()` method on just about every component, but the event continues to make it up to the Accordion.  Note: I've tried using DropdownButton and Dropdown with explicit inner components (Dropdown.Item, Menu, etc) with no difference in result.

I found a similar post here: https://github.com/react-bootstrap/react-bootstrap/issues/2327.  OP attempted to wrap the DropdownButton with a div with success, however I'm still having the same problem even after wrapping with a div.  Is it something I'm not setting correctly?  Thanks in advance.

### PR DESCRIPTION
**Pull request by kyletsang**
Fixes #4176

I moved the `SelectableContext` consumption to `NavDropdown` because it looks like this context is used in conjunction with `Nav` in triggering `onSelect` for `NavDropdown`s.

I've added the test in `Nav` to make sure I didn't break anything in that API and another test in `Accordion` to make sure the a dropdown would not trigger the accordion context.

This would also close the PR #4772.

### CODE REVIEW

File: src/NavDropdown.js [hunk 1]
```diff
@@ -57,28 +58,36 @@ const NavDropdown = React.forwardRef(
...
-      </Dropdown.Toggle>
+  ) => {
+    const onSelectCtx = useContext(SelectableContext);
+
+    const handleSelect = useEventCallback((key, event) => {
+      if (onSelectCtx) onSelectCtx(key, event);
+    });
+
+    return (
+      <Dropdown ref={ref} onSelect={handleSelect} {...props} as={NavItem}>
```
Comment (taion) [inline src/NavDropdown.js:69]: i wonder if we want to make `as` customizable in this context, then.

with this change, rendering a `<Dropdown>` with whatever styling inside a `<Nav>` now won't do the same thing as rendering a `<NavDropdown>`

which is probably okay, but maybe a bit more customizability here would help

**Comment by kyletsang** [comment]
@taion, I just revisited this and I realized anything that implements `AbstractNav` would suffer the same issue of collapsing the accordion inadvertently.  I'm thinking a better solution would be to wrap everything in `AccordionCollapse` with `<SelectableContext.Provider value={null}>`?

ie. in AccordionCollapse.js
```
return (
  <SelectableContext.Provider value={null}>
    <Collapse ref={ref} in={contextEventKey === eventKey} {...props}>
      <div>{React.Children.only(children)}</div>
    </Collapse>
  </SelectableContext.Provider>
);
```

What do you think?

**Comment by taion** [comment]
That could work. We might want to do that in general wherever we consume this context, then?

Could also use a different context here, but I guess that'd be breaking.

I'm not sure. Is it definitely the case that `AbstractNav` _shouldn't_ call into the parent `onSelect` from an accordion parent?

**Comment by kyletsang** [comment]
TBH, I can't think of any case where elements within the collapse would want to trigger the accordion parent.

**Comment by taion** [comment]
well, it's _sort of_ like nested navigation... idk

we can try that out, though

**Comment by kyletsang** [comment]
I'll update the PR anyway since the original solution doesn't cover all cases.  Others can chime in and we can close this if it's no good.

@jquense @bpas247 @mxschmitt

**Comment by eshwar-quartic** [comment]
@taion Any ETA on getting this merged?

**Comment by jquense** [comment]
I'm a bit concerned this change will break anyone using a custom dropdown in a navbar. I think maybe the underlying issue is we are reusing SelectableContext when we should probably have a different SelectableContext "instances" for each, lack of a better word, group of selectable behaviors. Then the contexts would talk past each other but maintain a unified public interface.

something like:
```js
NavSelectableContext = createSelectableContext();
AccordianSelectableContext = createSelectableContext()
```

**Comment by taion** [comment]
Oh, that sounds reasonable to me. Can we make that change for v1, though, or does it need to be deferred for v2?

**Comment by jquense** [comment]
I think this can go into a v1, it is maintaining the same API, and fixes a bug...is the SelectionContext public?

**Comment by taion** [comment]
It's not explicitly documented nor exposed at top-level. I think we may have pointed people toward it for cases where they need more fine-grained control, though.

**Comment by kyletsang** [comment]
Oops I forgot to update the title here - it no longer reflects the new change.  

What I ended up doing is wrapping the AccordionCollapse with a null SelectableContext.  This prevents the elements inside the collapse from grabbing the context.

Looking at the code I believe the only element that uses SelectableContext is the toggle.  I don't think the contents of the collapse need the root SelectableContext from Accordion.... does it?

@jquense

**Comment by tmm1** [comment]
Thanks for this fix! Any chance of a 1.3.1 release soon with this included?

**Comment by tmm1** [comment]
@taion friendly ping for a new release sometime :)

**Comment by kyletsang** [comment]
@tmm1 this is available in 1.4.0

**Comment by tmm1** [comment]
Thanks! I missed that on https://github.com/react-bootstrap/react-bootstrap/releases
