### PR TITLE
Rely on babel api instead of executing the babel cli

### LINKED ISSUE #754: Error during npm run build
[31mError: Command failed: ��ʱ��Ӧ�� <<��
 `babel  --out-file D:\www\javascript\temp\react-bootstrap\lib\factories\index.js <<EOF
 
import Accordion from './Accordion';

import Affix from './Affix';

import Alert from './Alert';

import Badge from './Badge';

import Button from './Button';

import ButtonGroup from './ButtonGroup';

import ButtonInput from './ButtonInput';

import ButtonToolbar from './ButtonToolbar';

import CollapsibleNav from './CollapsibleNav';

import Carousel from './Carousel';

import CarouselItem from './CarouselItem';

import Col from './Col';

import DropdownButton from './DropdownButton';

import DropdownMenu from './DropdownMenu';

import Glyphicon from './Glyphicon';

import Grid from './Grid';

import Input from './Input';

import Interpolate from './Interpolate';

import Jumbotron from './Jumbotron';

import Label from './Label';

import ListGroup from './ListGroup';

import ListGroupItem from './ListGroupItem';

import MenuItem from './MenuItem';

import Modal from './Modal';

import Nav from './Nav';

import Navbar from './Navbar';

import NavItem from './NavItem';

import ModalTrigger from './ModalTrigger';

import OverlayTrigger from './OverlayTrigger';

import PageHeader from './PageHeader';

import Panel from './Panel';

import PanelGroup from './PanelGroup';

import PageItem from './PageItem';

import Pager from './Pager';

import Popover from './Popover';

import ProgressBar from './ProgressBar';

import Row from './Row';

import SplitButton from './SplitButton';

import SubNav from './SubNav';

import TabbedArea from './TabbedArea';

import Table from './Table';

import TabPane from './TabPane';

import Thumbnail from './Thumbnail';

import Tooltip from './Tooltip';

import Well from './Well';

export default {

  Accordion,

  Affix,

  Alert,

  Badge,

  Button,

  ButtonGroup,

  ButtonInput,

  ButtonToolbar,

  CollapsibleNav,

  Carousel,

  CarouselItem,

  Col,

  DropdownButton,

  DropdownMenu,

  Glyphicon,

  Grid,

  Input,

  Interpolate,

  Jumbotron,

  Label,

  ListGroup,

  ListGroupItem,

  MenuItem,

  Modal,

  Nav,

  Navbar,

  NavItem,

  ModalTrigger,

  OverlayTrigger,

  PageHeader,

  Panel,

  PanelGroup,

  PageItem,

  Pager,

  Popover,

  ProgressBar,

  Row,

  SplitButton,

  SubNav,

  TabbedArea,

  Table,

  TabPane,

  Thumbnail,

  Tooltip,

  Well,

}
` (exited with error code 1)[39m
[31mError: Command failed: ��ʱ��Ӧ�� <<��
 `babel  --out-file D:\www\javascript\temp\react-bootstrap\lib\factories\index.js <<EOF
 
import Accordion from './Accordion';

import Affix from './Affix';

import Alert from './Alert';

import Badge from './Badge';

import Button from './Button';

import ButtonGroup from './ButtonGroup';

import ButtonInput from './ButtonInput';

import ButtonToolbar from './ButtonToolbar';

import CollapsibleNav from './CollapsibleNav';

import Carousel from './Carousel';

import CarouselItem from './CarouselItem';

import Col from './Col';

import DropdownButton from './DropdownButton';

import DropdownMenu from './DropdownMenu';

import Glyphicon from './Glyphicon';

import Grid from './Grid';

import Input from './Input';

import Interpolate from './Interpolate';

import Jumbotron from './Jumbotron';

import Label from './Label';

import ListGroup from './ListGroup';

import ListGroupItem from './ListGroupItem';

import MenuItem from './MenuItem';

import Modal from './Modal';

import Nav from './Nav';

import Navbar from './Navbar';

import NavItem from './NavItem';

import ModalTrigger from './ModalTrigger';

import OverlayTrigger from './OverlayTrigger';

import PageHeader from './PageHeader';

import Panel from './Panel';

import PanelGroup from './PanelGroup';

import PageItem from './PageItem';

import Pager from './Pager';

import Popover from './Popover';

import ProgressBar from './ProgressBar';

import Row from './Row';

import SplitButton from './SplitButton';

import SubNav from './SubNav';

import TabbedArea from './TabbedArea';

import Table from './Table';

import TabPane from './TabPane';

import Thumbnail from './Thumbnail';

import Tooltip from './Tooltip';

import Well from './Well';

export default {

  Accordion,

  Affix,

  Alert,

  Badge,

  Button,

  ButtonGroup,

  ButtonInput,

  ButtonToolbar,

  CollapsibleNav,

  Carousel,

  CarouselItem,

  Col,

  DropdownButton,

  DropdownMenu,

  Glyphicon,

  Grid,

  Input,

  Interpolate,

  Jumbotron,

  Label,

  ListGroup,

  ListGroupItem,

  MenuItem,

  Modal,

  Nav,

  Navbar,

  NavItem,

  ModalTrigger,

  OverlayTrigger,

  PageHeader,

  Panel,

  PanelGroup,

  PageItem,

  Pager,

  Popover,

  ProgressBar,

  Row,

  SplitButton,

  SubNav,

  TabbedArea,

  Table,

  TabPane,

  Thumbnail,

  Tooltip,

  Well,

}
` (exited with error code 1)
    at ChildProcess.exithandler (child_process.js:647:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Socket.<anonymous> (child_process.js:966:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)[39m

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "D:\\bin\\nodejs\\\\node.exe" "D:\\bin\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v0.10.28
npm ERR! npm  v2.11.0
npm ERR! code ELIFECYCLE
npm ERR! react-bootstrap@0.23.0 build: `babel-node tools/build-cli.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-bootstrap@0.23.0 build script 'babel-node tools/build-cli.js'.
npm ERR! This is most likely a problem with the react-bootstrap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/build-cli.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-bootstrap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\www\javascript\temp\react-bootstrap\npm-debug.log

### PR DESCRIPTION
**Pull request by Cellule**
fixes #754
Implements some utility function to build with babel using the api.
`buildGlob` is not use at this moment and can be removed if you wish. It was mostly an attempt to mimic babel-cli.
`'./test/server/*Spec.js'` was not recognised by mocha. I'm not sure if it's particularly related to Windows, but it works this way and I'm confident it will work for Linux.

### CODE REVIEW

File: tools/amd/build.js [hunk 1]
```diff
@@ -37,7 +38,7 @@ export default function BuildBower() {
     .then(() => Promise.all([
       bowerConfig(),
       generateFactories(factoriesDestination, babelOptions),
-      exec(`babel ${babelOptions} ${srcRoot} --out-dir ${libDestination}`),
+      buildFolder(srcRoot, libDestination, babelOptions),
```
Comment (mtscout6) [inline tools/amd/build.js]: What is the thought behind not using babel's cli? I don't understand why the more complicated approach is necessary. Does the babel-cli not work on windows?

File: package.json [hunk 2]
```diff
@@ -10,7 +10,7 @@
   "scripts": {
     "build": "babel-node tools/build-cli.js",
     "test-watch": "karma start",
-    "test": "npm run lint && npm run build && karma start --single-run && _mocha --compilers js:babel-core/register './test/server/*Spec.js'",
+    "test": "npm run lint && npm run build && karma start --single-run && _mocha --compilers js:babel-core/register test/server/*Spec.js",
```
Comment (AlexKVal) [inline package.json]: :+1:

File: tools/amd/build.js (hunk 1 above)
Comment (Cellule) [inline tools/amd/build.js]: The biggest problem with the cli is that there is no way (that I know) to run it from stdin in a cross platform way.
Therefore, I thought using the api instead would be cleaner. Since I changed to use the api for factories, it would be more uniform to use it everywhere.

That said, I think the solution to have write a temporary file then run babel and delete the temp file is also valid. I wanted to show another option to see which we prefer.

**Comment by mtscout6** [comment]
First off I have to tip my hat off to you because this runs about 45 seconds faster than our current build. That had me scared at first but I check the resulting `lib/` and `amd/` folders with [Beyond Compare](http://www.scootersoftware.com/index.php) against the previous implementation and they both have the same output. At the same time though I'm baffled as to why this is faster especially when you are doing synchronous file reads which is a blocking IO operation ([here for example](https://github.com/Cellule/react-bootstrap/blob/babel_api/tools/buildBabel.js#L15)). I would have expected that to be slower. I also would have expected this to be slower since we are now doing more in this single process in lieu of fanning out to multiple processes to handle this. It may be the case that the overhead of spawning those processes is why this is faster?

With that said though I worry about the maintenance cost that this will incur. We are opening ourselves up to more difficult upgrades to babel. The footprint is small, but could get broader and more difficult to wield as time goes on. For example the way with with you [load](https://github.com/Cellule/react-bootstrap/blob/babel_api/tools/buildBabel.js#L10) the `.babelrc` file is not a documented approach http://babeljs.io/docs/usage/babelrc/. Since it is not documented I could see the babel team changing this and not seeing the need for a proper version bump.

The alternative approach as prescribed in #769 is much simpler and still just as slow as it is today. The benefit being that the footprint with which we integrate with babel is smaller and perceivably easier to maintain in the long run.

The question here is perceived ease of maintenance. Is this something that the babel team is likely to change? Probably not, and if so it may not change too drastically. Or is the improved speed with which we compile going to outweigh that cost.

@react-bootstrap/collaborators Thoughts?

**Comment by mathieumg** [comment]
I see he hasn't answered yet, but when I spoke with @Cellule this weekend he mentioned that another way to achieve this would be to take the idea of the original command line (pipe something to the Babel CLI through stdin) and do it with the Node.js child process API instead: https://nodejs.org/api/child_process.html#child_process_child_stdin

That would certainly be the cleanest of all options: no API internals, no temporary files and OS portability. I don't know where it would stand in terms of performance, however.

**Comment by mtscout6** [comment]
@Cellule Looks like there is a merge conflict with master, can you rebase on the latest?

**Comment by mtscout6** [comment]
Thanks for tackling this @Cellule!

**Comment by AlexKVal** [comment]
@Cellule thank you for speed it up :rocket:

**Comment by taion** [comment]
>Trace: I know someone out there is hotlinking straight to this file. This is a PRIVATE API. I hate you, but I wont break your code just because you're a programmer who practices bad habits.

Heh.

**Comment by mtscout6** [comment]
@taion Where did you see that?

**Comment by taion** [comment]
https://github.com/babel/babel/blob/c9286a1de1f7ef8e88396414c23233918d2f868b/src/babel/tools/resolve-rc.js

As of the latest Babel release.
