### PR TITLE
fix(NavbarOffcanvas): fix rendering of nav items when expand is used

### LINKED ISSUE #6309: Navbar Offcanvas not showing nav items with `expand` prop
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

The offcanvas navbar component found here https://react-bootstrap.github.io/components/navbar/#offcanvas is very similar to the one found in regular bootstrap - and I've tried to make this one function like the one in regular bootstrap, so once your window is at a certain size (expand="lg"), so 992px, the navbar will then collapse into its offcanvas format, rather than appearing as a normal navbar - but instead the normal navbar doesn't appear, instead disappearing and leaving me with just a gray bar.

### Expected behavior

I expected the navbar to function like so:

https://getbootstrap.com/docs/5.1/examples/offcanvas-navbar/#

### To Reproduce

1. Go to https://react-bootstrap.github.io/components/navbar/#offcanvas
2. Replicate the code
3. Change "expand={false}" to expand="lg"
4. Note that the navbar doesn't function as original bootstrap intended.

### Reproducible Example

https://react-bootstrap.github.io/components/navbar/#offcanvas

### Screenshots

Collapsed

Non Collapsed

Note that until it is collapsed, nothing appears on the navbar besides the brand, which is outside of the offcanvas.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.3.0

### What version of Bootstrap are you using?

5.1.3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kyletsang**
Fixes #6309

When the navbar hits the expand breakpoint, it will render the children into a div instead of using the Offcanvas component to do it.  We don't need the functionality when the nav items are shown this way anyway.  One thing that needs to be done is to add a default breakpoint size for xxl in @restart/hooks.

I think this approach should be ok?  Will add tests later after review.

### CODE REVIEW

File: src/NavbarOffcanvas.tsx [hunk 1]
```diff
@@ -1,13 +1,80 @@
...
+        restoreFocusOptions={restoreFocusOptions}
+        onShow={onShow}
+        onHide={onHide}
+        onEscapeKeyDown={onEscapeKeyDown}
+        onEnter={onEnter}
+        onEntering={onEntering}
+        onEntered={onEntered}
+        onExit={onExit}
+        onExiting={onExiting}
+        onExited={onExited}
```
Comment (golota60) [inline src/NavbarOffcanvas.tsx:74]: why change this from `{...props}`? They're being forwarded anyway

**Review by golota60 — APPROVED** [review]
lgtm, left one nitpick/question

File: src/NavbarOffcanvas.tsx (hunk 1 above)
Comment (golota60) [reply src/NavbarOffcanvas.tsx:74]: i mean _most_ of these

Comment (kyletsang) [reply src/NavbarOffcanvas.tsx:74]: lol yeah it's a bit ugly.  I pulled it out because I also spread the remainder of the props into the div above for the navbar expand case.
