### PR TITLE
Fix(Unable to add custom styles to PageItem Component)

### LINKED ISSUE #5950: Unable to add custom styles to PageItem Component
## Describe the bug

There is incomplete API to allow adding custom styles to the `<Component>` inside the `<PageItem>`. Looking at the [source code](https://github.com/react-bootstrap/react-bootstrap/blob/d91fbf1c443b230cc7f4852ea4f5e43814da99f8/src/PageItem.tsx#L60), there there is no `className` or `style` prop that is passed to the `<Component>` to allow for custom styles to be applied. 

Currently, I can modify the class `.page-link`, but I don't like overriding classes globally.

## Expected behavior

It would be ideal to be able to pass styles or a className as a prop to modify the underlying `<Component>` inside `<PageItem>`

app.tsx

```tsx
import React from 'react';
import PageItem, { PageItemProps } from 'react-bootstrap/PageItem';

export type PaginationItemProps = PageItemProps;

export const PaginationItem: React.FC<PaginationItemProps> = (props) => {
    return (
        <PageItem {...props} active componentStyle={...} componentClassName="" />
    );
};
```

react-bootstrap.PageItem.tsx

```tsx
const PageItem: BsPrefixRefForwardingComponent<'li', PageItemProps> =
  React.forwardRef<HTMLLIElement, PageItemProps>(
    (
      {
        active,
        disabled,
        className,
        style,
        activeLabel,
        children,
        componentStyle,
        componentClassName,
        ...props
      }: PageItemProps,
      ref,
    ) => {
      const Component = active || disabled ? 'span' : SafeAnchor;
      return (
        <li
          ref={ref}
          style={style}
          className={classNames(className, 'page-item', { active, disabled })}
        >
          { /* UPDATE Component props below */}
          <Component className={'page-link', componentClassName} style={componentStyle} disabled={disabled} {...props}>
            {children}
            {active && activeLabel && (
              <span className="visually-hidden">{activeLabel}</span>
            )}
          </Component>
        </li>
      );
    },
  );
```

## Environment (please complete the following information)

- React-Bootstrap Version: 1.6.1

## Additional context

Thanks for this awesome repo! I would be willing to make a PR. Thanks!

### PR DESCRIPTION
**Pull request by devmuhnnad**
This fixes #5950 

When using Bootstrap Pagination, There is an incomplete API to allow adding custom styles to the ``<Component>`` inside the ``<PageItem>``. there is no className or style prop that is passed to the <Component> to allow for custom styles to be applied, so The developer can't change the color of the ``<a>``  tag inside of the ``<PageItem>`` for example!

I have solved the issue by creating a new two props ( innerStyle and innerClassName ), they are passed to the ``<Component>`` inside of ``<PageItem>``

Thanks.

PART OF GTC OPEN SOURCE INTIATIVE

### CODE REVIEW

File: src/PageItem.tsx [hunk 1]
```diff
@@ -13,6 +13,8 @@ export interface PageItemProps
   active?: boolean;
   activeLabel?: string;
   href?: string;
+  innerStyle?: React.CSSProperties;
```
Comment (kyletsang) [inline src/PageItem.tsx:16]: Can you rename these to `linkStyle` and `linkClassName`?  It's more descriptive of where the prop is applied.  Also please add tests for the two props

**Comment by devmuhnnad** [comment]
Great suggestion, it's done.

**Review by kyletsang — APPROVED** [review]
