### PR TITLE
Fix logic for determining child active state

### LINKED ISSUE #2201: 0.30.3 breaks react-router-bootstrap LinkContainers inside NavDropdown
I have `<LinkContainer>` elements under `<NavDropdown>`s. When I updated to 0.30.3, the `<LinkContainers>`s will have `active={false}` props passed on them. This breaks them because they will never show up as active now.

Rolling back to 0.30.2 fixes the problem.

### PR DESCRIPTION
**Pull request by taion**
Fixes #2201

### CODE REVIEW

**Comment by jquense** [comment]
Wait what's wrong with `some` here?

**Comment by jquense** [comment]
also what is the deal with  CI recently

**Comment by taion** [comment]
That `some` call will return `false` if all the `children` have `props.active === undefined`.

File: docs/src/SubNav.js [hunk 1]
```diff
@@ -53,9 +53,16 @@ class SubNav extends React.Component {
...
-        this.isActive(child, activeKey, activeHref)
-      ));
+      let active;
+      ValidComponentChildren.forEach(props.children, (child) => {
+        if (active === undefined) {
+          active = this.isActive(child, activeKey, activeHref);
+        }
+      });
+
+      if (active !== undefined) {
```
Comment (jquense) [inline docs/src/SubNav.js]: if you already have this check maybe use `some` above? that or just add a note to the nuance of this. it wasn't obvious to me why this was needed, re: undefined vs false

Comment (taion) [inline docs/src/SubNav.js]: I'm not sure what you mean – how would I use `some`?

Comment (taion) [inline docs/src/SubNav.js]: The issue is that `[undefined].some(Boolean)` is `false`.

Comment (jquense) [inline docs/src/SubNav.js]: you can use to check if any child is active is so return true otherwise undefined? seems like all you need is the if block guarding against returning false right?

Comment (taion) [inline docs/src/SubNav.js]: I want the first defined value if there is one. If any child has active false, this function should return false.

Comment (taion) [inline docs/src/SubNav.js]: Oh, actually, I see what you mean. I don't actually need that.

**Comment by taion** [comment]
Updated.

**Comment by jquense** [comment]
lgtm
