### PR TITLE
[fixed] Only calculate overlay position on display

### LINKED ISSUE #1018: Transition/Position Nesting on Overlays
Placeholder issue for some final v0.24 fixes.

### PR DESCRIPTION
**Pull request by taion**
Fixes #1018

This restores the old behavior where we only calculate position initially (and when the target changes).

I also ended up modifying the `Transition` implementation a bit to make the state tracking a bit more explicit.

### CODE REVIEW

**Comment by taion** [comment]
There were a few minor race conditions in `Transition` around rapid state changes, which this implementation should resolve.

File: src/Collapse.js [hunk 1]
```diff
@@ -115,84 +115,82 @@ class Collapse extends React.Component {
 
 Collapse.propTypes = {
   /**
-   * Collapse the Component in or out.
+   * Whether the component is entered; triggers the enter or exit animation
```
Comment (AlexKVal) [inline src/Collapse.js]: some vague description.
sorry but I did not get it. :sweat: 
may be add a couple simple one liner examples ?

--
though maybe it's just advanced English

File: src/Collapse.js [hunk 2]
```diff
@@ -115,84 +115,82 @@ class Collapse extends React.Component {
...
-  duration:          React.PropTypes.number,
+  unmountOnExit: React.PropTypes.bool,
 
   /**
-   * Specifies the dimension used when collapsing.
-   *
-   * _Note: Bootstrap only partially supports 'width'!
-   * You will need to supply your own css animation for the `.width` css class._
+   * Whether transition in should run when the Transition component mounts, if
+   * the component is initially entered
```
Comment (AlexKVal) [inline src/Collapse.js]: `transition in` => `transition 'in'` ?
`is initially entered` => `is initially in 'entered' state` ?

File: src/Collapse.js [hunk 3]
```diff
@@ -115,84 +115,82 @@ class Collapse extends React.Component {
...
-   * Specify whether the transitioning component should be unmounted (removed from the DOM) once the exit animation finishes.
+   * The dimension used when collapsing
+   *
+   * _Note: Bootstrap only partially supports 'width'!
+   * You will need to supply your own CSS animation for the `.width` CSS class._
    */
-  unmountOnExit:     React.PropTypes.bool,
+  dimension: React.PropTypes.oneOfType([
+    React.PropTypes.oneOf(['height', 'width']),
+    React.PropTypes.func
```
Comment (AlexKVal) [inline src/Collapse.js]: this `function` variant is not documented.
Is it private ?

File: src/Fade.js [hunk 4]
```diff
@@ -2,87 +2,77 @@ import React from 'react';
 import Transition from './Transition';
 
 class Fade extends React.Component {
-
-  constructor(props, context){
-    super(props, context);
-  }
```
Comment (AlexKVal) [inline src/Fade.js]: can I read somewhere about it ?

File: src/Fade.js [hunk 5]
```diff
@@ -2,87 +2,77 @@ import React from 'react';
...
         enteringClassName='in'
       >
-        { this.props.children }
+        {this.props.children}
       </Transition>
     );
   }
 }
 
+// Explicitly copied from Transition for doc generation.
```
Comment (AlexKVal) [inline src/Fade.js]: I would mark it for future:
`TODO: remove doc generation duplication with Transition, when some mechanic for it is added`
(phrasing could be better o/c)

File: src/Position.js [hunk 6]
```diff
@@ -15,33 +15,35 @@ class Position extends React.Component {
...
+    }
   }
 
   render() {
-    let { children, ...props } = this.props;
-    let { positionLeft, positionTop, ...arrows } = this.props.target ? this.state : {};
+    const {children, ...props} = this.props;
+    const {positionLeft, positionTop, ...arrowPosition } = this.state;
 
+    const child = React.Children.only(children);
```
Comment (AlexKVal) [inline src/Position.js]: :+1:

File: src/Overlay.js [hunk 7]
```diff
@@ -42,56 +35,63 @@ class Overlay extends React.Component {
...
-    let child = null;
-
-    if ( Transition === true ){
+    if (Transition === true) {
       Transition = Fade;
     }
 
-    if (props.show || (Transition && this.state.exiting && !this.state.exited)) {
+    // Don't un-render the overlay while it's transitioning out.
+    const mountOverlay = props.show || (Transition && !this.state.exited);
```
Comment (AlexKVal) [inline src/Overlay.js]: :+1:

File: src/Position.js [hunk 8]
```diff
@@ -49,55 +51,62 @@ class Position extends React.Component {
...
-  _maybeUpdatePosition(){
-    if ( this._needsFlush ) {
-      this._needsFlush = false;
-      this._updatePosition();
+  getTargetSafe(props) {
+    if (!props.target) {
+      return null;
     }
+
+    return props.target(props);
```
Comment (AlexKVal) [inline src/Position.js]: why not just ?
```js
getTargetSafe(props) {
  return props.target ? props.target(props) : null;
}
```

File: src/Position.js [hunk 9]
```diff
@@ -49,55 +51,62 @@ class Position extends React.Component {
...
+      container,
+      props.containerPadding
+    ));
   }
 }
 
 Position.propTypes = {
   /**
-   * The target DOM node the Component is positioned next too.
+   * Function mapping props to DOM node the component is positioned next to
```
Comment (AlexKVal) [inline src/Position.js]: :+1:

File: src/Position.js [hunk 10]
```diff
@@ -49,55 +51,62 @@ class Position extends React.Component {
...
-  container:        CustomPropTypes.mountable,
+  container: CustomPropTypes.mountable,
   /**
-   * Distance in pixels the Component should be positioned to the edge of the Container.
+   * Minimum spacing in pixels between container border and component border
    */
   containerPadding: React.PropTypes.number,
   /**
-   * The location that the overlay should be positioned to its target.
+   * How to position the component relative to the target
```
Comment (AlexKVal) [inline src/Position.js]: :+1:

File: src/Transition.js [hunk 11]
```diff
@@ -2,284 +2,274 @@ import React from 'react';
...
+  render() {
+    const status = this.state.status;
+    if (status === UNMOUNTED) {
+      return null;
     }
 
-    else if (!this.state.in && this.state.transitioning) {
-      classes = this.props.exitingClassName;
+    const {children, className, style, ...childProps} = this.props;
+    Object.keys(Transition.propTypes).forEach(key => delete childProps[key]);
```
Comment (AlexKVal) [inline src/Transition.js]: :+1:  instead of `omit()`

File: src/Transition.js [hunk 12]
```diff
@@ -2,284 +2,274 @@ import React from 'react';
...
+
+    let transitionClassName;
+    if (status === EXITED) {
+      transitionClassName = this.props.exitedClassName;
+    } else if (status === ENTERING) {
+      transitionClassName = this.props.enteringClassName;
+    } else if (status === ENTERED) {
+      transitionClassName = this.props.enteredClassName;
+    } else if (status === EXITING) {
+      transitionClassName = this.props.exitingClassName;
```
Comment (AlexKVal) [inline src/Transition.js]: why not continue and not use `switch/case` then ?

File: src/Transition.js [hunk 13]
```diff
@@ -2,284 +2,274 @@ import React from 'react';
...
-   * A callback fired after "exit" classes are applied
+   * Callback fired after the "exited" classes are applied
    */
-  onExited:    React.PropTypes.func
+  onExited: React.PropTypes.func
 };
 
-// name the function so it is clearer in the documentation
-const noop = ()=>{};
+// Name the function so it is clearer in the documentation
```
Comment (AlexKVal) [inline src/Transition.js]: :+1:

**Comment by AlexKVal** [comment]
I think adding disabling eslint comment should be enough.
```js
const {children, className, style, ...childProps} = this.props; // eslint-disable-line react/prop-types
```
to satisfy
screen shot 2015-07-20 at 3 22 50 pm

and it is good to go :sparkle:  :cherries: 

--
I like the idea to use constants here
```js
export const EXITED = 1;
export const ENTERING = 2;
export const ENTERED = 3;
export const EXITING = 4;
```
Code readability and tests readability now is much better.

Even I started to understand at some degree how it works :blush: 
(though it definitely needs some kind of tutorial with diagrams, but it is another issue o/c.
I believe when I am totally grasp mechanic of these components, I could write one for beginners like me)

File: src/Fade.js (hunk 5 above)
Comment (AlexKVal) [inline src/Fade.js]: and maybe add https://github.com/react-bootstrap/react-bootstrap/issues/977 to this TODO

File: src/Fade.js (hunk 4 above)
Comment (jquense) [inline src/Fade.js]: if you only call `super` in the constructor with the same arguments its the same thing as not having it. Classes will essentially create that constructor automatically for you.

File: src/Overlay.js [hunk 14]
```diff
@@ -42,56 +35,63 @@ class Overlay extends React.Component {
...
-      // Position the child before the animation to avoid `null` DOM nodes
+    if (Transition) {
+      // This animates the child by injecting props, so it must be inner-most.
       child = (
-        <Position {...{ container, containerPadding, target, placement }}>
-          { child }
-        </Position>
+        <Transition
+          in={props.show}
+          transitionAppear
```
Comment (jquense) [inline src/Overlay.js]: why remove the `props.show` here? Originally it was there because you only want the fade in animation to run on mount. if `in=false` initially this will show the overlay then fade it out, instead of just starting closed. Is that the behavior we want?

File: src/Overlay.js (hunk 7 above)
Comment (jquense) [inline src/Overlay.js]: What was the rational for removing `this.state.exiting`? I originally had the code like this, but ran into a bug...that I can't remember, that this additional check fixed

File: src/Transition.js [hunk 15]
```diff
@@ -2,284 +2,274 @@ import React from 'react';
...
+          this.props.onEntered(node);
+        });
       });
-    };
-
-    if (maybeNode) {
-      enter(maybeNode);
-    }
-    else if (this.props.unmountOnExit) {
-      this._ensureNode(enter);
```
Comment (jquense) [inline src/Transition.js]: sorry its a bit early for me still...in the new code how is this cases handled, where a node has exited and unmounted and now needs to enter, wouldn't the node still be null here, or am i just not tracking the logic through well enough.

**Comment by jquense** [comment]
looks great :) nice and clean. Tangential question why remove all the Fade/Collapse specific documentation comments with the base Transition ones (in which case you can just leave them out completely)?

File: src/Transition.js [hunk 16]
```diff
@@ -2,284 +2,274 @@ import React from 'react';
...
+    return React.cloneElement(
+      child,
+      {
+        ...childProps,
+        className: classnames(
+          child.props.className,
+          className,
+          transitionClassName
+        ),
+        style: {...child.props.style, ...style}
```
Comment (jquense) [inline src/Transition.js]: why this? My thought was that if someone wanted to style the child they can just add it there, instead of introducing an additional input vector. I don't have any strong opinion here, just wondering

File: src/Fade.js (hunk 5 above)
Comment (taion) [inline src/Fade.js]: This is not so easy - the current metadata parser actually crashes if I try to do this the "obvious" way with e.g. `_.omit`.

File: src/Position.js (hunk 8 above)
Comment (taion) [inline src/Position.js]: I think it's a little more clear to write "exceptional" cases as traps at the start of a function rather than branches, e.g. I always use something like

```js
if (thingsAreMessedUp) {
  return;
}

// do actual work
```

File: src/Transition.js (hunk 12 above)
Comment (taion) [inline src/Transition.js]: I had it initially - a lot of people don't like `switch`/`case`, though, so I thought this was a bit more kosher.

File: src/Transition.js (hunk 16 above)
Comment (taion) [inline src/Transition.js]: This actually broke the custom overlay example - I'd changed it to `Position > Transition > {node}`, and the styles from `Position` were clobbering the ones on the node.

That said, looking at the code now, it's actually just fine if I change it back to `Transition > Position > {node}`, so I'm going to get rid of this.

File: src/Transition.js (hunk 15 above)
Comment (taion) [inline src/Transition.js]: For the `unmountAtExit`, the flow on `in` getting set is:

1. In `componentWillReceive` props, we hit the `unmountAtExit` + `UNMOUNTED` case, and set the state to `EXITED`
2. In `render`, we show the component in the exited state
3. In `componentDidUpdate` (after the DOM has already reflowed), we hit the case where we are `in` and `EXITED`, and kick off the enter animation - at this point the node exists again

File: src/Fade.js (hunk 5 above)
Comment (jquense) [inline src/Fade.js]: I have been thinking about this...if we had a standard omit, we could teach the metadata about it. Right now tho it will probably choke on anything that isn't an object literal, so you'd need to use a spread like: `..._.omit(blah, ['bah'])`

File: src/Overlay.js (hunk 14 above)
Comment (taion) [inline src/Overlay.js]: In both versions of the code, we only hit this branch if we're showing or exiting the overlay.

I might be misunderstanding the intention of `transitionAppear`, but I interpreted it as meaning "if the component is `in` on mounting, mount it in the exited state, but transition to entering immediately after the initial render", and nothing else.

**Comment by taion** [comment]
RE: custom doc removal - laziness/tiredness on my part, will add back.

File: src/Transition.js (hunk 15 above)
Comment (jquense) [inline src/Transition.js]: ahhh ok so when it is going to transition back in, you change it from `UNMOUNTED` to `EXITED`, nice. :)

File: src/Overlay.js (hunk 14 above)
Comment (jquense) [inline src/Overlay.js]: I was more or less trying to copy the meaning from [CSSTransitionGroup](http://facebook.github.io/react/docs/animation.html#animate-initial-mounting) which, now that I think about it, only apply for entering, since state is determined by whether children exist there. Which is to say matches your interpretation.

I was thinking originally though that since the `in` prop determines initial state, it could also apply to the inverse, i.e:  "if the component is not `in` on mounting, mount it in the entered state, but transition to exiting immediately after the initial render". That was the original behavior. That being said its a totally valid to question whether that makes any sense. Would you ever want to animate out on mount? I went for just allowing it for flexibility, but I can't personally think of an actual use case...

File: src/Transition.js (hunk 15 above)
Comment (taion) [inline src/Transition.js]: Yes - let me rewrite this to be more explicit in that it's separately handling the `unmountAtExit` and `transitionAppear` cases.

File: src/Overlay.js (hunk 14 above)
Comment (taion) [inline src/Overlay.js]: It shouldn't be difficult to add it back, but I can't think of a good use case for wanting to do so - can add it back if it comes up.

File: src/Overlay.js (hunk 7 above)
Comment (taion) [inline src/Overlay.js]: I think there were a few edge cases around the "exited" trigger firing early from `onExited` - since I now explicitly cancel the chained callbacks in `Transition`, those no longer come up.

**Comment by taion** [comment]
Added commit with fixes to above.

**Comment by taion** [comment]
Added a test to handle a bug in my `unmountOnExit` handling.

File: src/Fade.js (hunk 4 above)
Comment (AlexKVal) [inline src/Fade.js]: Gotcha.

**Comment by AlexKVal** [comment]
Thank you for clear doc descriptions for props :+1: 
Now everything is cleaner.

**Comment by jquense** [comment]
This looks great! Thanks for cleaning it up, it's really slick now. I haven't had a chance to actually try it out. but should have a moment to do so in a bit.

**Comment by AlexKVal** [comment]
OT: 
> I switched everything to use expect for consistency. should doesn't work for e.g. null values, which I use to assert non-mounted-ness on the DOM.

What do you thing about I re-write all other tests from `should` to `expect` and somehow prevent (by eslint) all future `should` usage ?

**Comment by taion** [comment]
@AlexKVal 

I replaced `should` with `expect` because I started out with `should`, realized it didn't work, and then did a regex search-and-replace that changed other instances in the file, so I figured "what the hell" and just made everything consistent (previously it was using a mix of `should` and `assert`).

I'd prefer to use `expect` everywhere, but it's pure bikeshedding, and doesn't materially affect the readability of the code. I'd personally be mildly supportive of making such a change to make our test code more consistent and more easily scannable, but I don't think it's a big deal.

**Comment by AlexKVal** [comment]
My motive for `should` => `expect` is exactly this:
> should doesn't work for e.g. null values

thus to prevent such subtle bugs.

**Comment by taion** [comment]
It won't be a subtle bug though, for a test (unless the test is somehow non-deterministic). The test just won't work.

@jquense Did you get a chance to take a look? Waiting to fix the positioning bit before releasing v0.24.

**Comment by jquense** [comment]
went through it on the docs site. Looks great, just one thought. since the updatePosition call is being processed in `componentWillReceiveProps` there might be a chance that that new target doesn't exist yet right, if it was just mounted?

If that's not an issue then :shipit:

**Comment by taion** [comment]
That's a good point. If the target gets switched to point to a ref of a component mounted in the same render cycle, this code will probably break. Let me not try to be as clever in this code.

**Comment by taion** [comment]
@jquense Fixed the Position recalculation.

**Comment by jquense** [comment]
:shipit: :shipit:

**Comment by taion** [comment]
I'm really sorry - one more change incoming. Current implementation is pretty dumpster tier now that I think about it. Sorry to waste your time.

**Comment by taion** [comment]
Okay, last change for real this time - instead of trying to do weird checks on the value of the `target` function, just cache the last target element, and check to see if it changes.

**Comment by jquense** [comment]
LGTM

**Comment by taion** [comment]
LF:KDJSF

**Comment by AlexKVal** [comment]
> LF:KDJSF

Did you mean all those `!fixup` and `fixup!` ? :smile: 
screen shot 2015-07-22 at 3 24 00 pm

**Comment by AlexKVal** [comment]
But hey !!
`v0.24` finally is out :tada: :tada: :tada: :sparkle: :sparkles: :sparkle:
