### PR TITLE
fix: prioritize poppers position prop in overlaytrigger

### LINKED ISSUE #6173: Arrow placement in overlay not working with `flip` modifier
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Classname does not change when overlay position changes if flip is enabled. And also on older versions of bootstrap, react-bootstrap everything works perfectly. I hope you fix this, thanks!

### Expected behavior

It was expected that when I passed prop flip = {true} and position = {'top'} my arrow in overlay would change its position depending on how much I scrolled.

### To Reproduce

_No response_

### Reproducible Example

This example reflects the error, as well as the solution that I use on my project.
https://codesandbox.io/s/festive-clarke-s9pud?file=/src/App.js

### Screenshots

_No response_

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of React-Bootstrap are you using?

2.1.0

### What version of Bootstrap are you using?

5.1.3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by golota60**
Fixes #6173. What was happening is that `placement` prop was being passed to `BaseOverlay` and then passed  to the `overlay` prop, ignoring popper object, which in turn resulted in hard-coded the `placement` property

### CODE REVIEW

File: src/Overlay.tsx [hunk 1]
```diff
@@ -181,18 +181,20 @@ const Overlay = React.forwardRef<HTMLElement, OverlayProps>(
       >
         {(overlayProps, { arrowProps, placement, popper: popperObj, show }) => {
           wrapRefs(overlayProps, arrowProps);
+          // Need to get placement from popper object first, handling case when overlay is flipped using 'flip' prop
+          const updatedPlacement = popperObj?.placement || placement;
```
Comment (kyletsang) [inline src/Overlay.tsx:185]: Hmm I wonder if we need to fallback to `placement` here.

I think(?) popper's placement should always be defined.

I think this might be enough `const updatedPlacement = popperObj?.placement;`

Comment (golota60) [reply src/Overlay.tsx:185]: i think you're right, will change

**Review by kyletsang — APPROVED** [review]
