### PR TITLE
fix: Fix clearing nextDirectionRef in <Carousel>

### LINKED ISSUE #5319: Carousel is not correctly sliding from first index to last in 'prev' direction
When on the first slide and triggering a slide event in 'prev' direction, the carousel slides to the correct element, the last slide, but with a 'next' animation. This can, for example, be observed in the documentation here:

https://react-bootstrap.github.io/components/carousel/#example

The effect is most apparent when repeatedly sliding to the previous slide. The transition from first to last is simply off.

For comparison the expected behavior from the Bootstrap carousel:

https://getbootstrap.com/docs/4.0/components/carousel/#with-controls

Unfortunately my knowledge in this area is so limited that I can't even find the event handler responsible for the actual transition, so I don't actually know where to look for this, but maybe one of you guys know why this is happening.

I'm using v1.2.2. Here is an example (not sure if it's the same version) https://codesandbox.io/s/runtime-grass-l2cg4?file=/package.json

related to https://github.com/react-bootstrap/react-bootstrap/issues/3654

### PR DESCRIPTION
**Pull request by taion**
Fixes #5319

### CODE REVIEW

File: src/Carousel.tsx [hunk 1]
```diff
@@ -265,6 +267,12 @@ function CarouselFunc(uncontrolledProps: CarouselProps, ref) {
     setRenderedActiveIndex(activeIndex || 0);
   }
 
+  useEffect(() => {
+    if (shouldClearNextDirection) {
+      nextDirectionRef.current = null;
+    }
```
Comment (kyletsang) [inline src/Carousel.tsx:273]: Tested the branch and this statement isn't being triggered for me.  It appears that `shouldClearNextDirection` is getting reset to `false` prior to running `useEffect`

Comment (taion) [reply src/Carousel.tsx:273]: it's closing over the value from the most recent "render" pass. the issue is that strictmode is happier about discarding render results... so this is the side effect we need to put into `useEffect`

you can also repro the bug just by wrapping our example in a `<React.StrictMode>`

Comment (taion) [reply src/Carousel.tsx:273]: and at least on my side, this fixes things

Comment (kyletsang) [reply src/Carousel.tsx:273]: I ran the example without strictmode in my case, so since the directionref isn't being cleared, skipping slides using the indicators on the bottom uses the wrong direction animation.  

Sliding on edges using left/right is fixed tho

Comment (taion) [reply src/Carousel.tsx]: I think this is fixed now! Could you take another look?

Comment (kyletsang) [reply src/Carousel.tsx]: Using carousel indicators still moves in wrong direction :(

Attaching gif:

carousel

Comment (taion) [reply src/Carousel.tsx]: It seems to work for me: https://gfycat.com/annualtautgreatargus

How did you get that repro?

Comment (kyletsang) [reply src/Carousel.tsx]: Huh weird.  I just ran the docs locally from this branch.  Ran the uncontrolled example without strictmode

Windows 10
Chrome Version 84.0.4147.105
Firefox 79.0 (64-bit)

Comment (taion) [reply src/Carousel.tsx]: I can't reproduce it on either Chrome or Firefox. Do you see it on https://deploy-preview-5322--react-bootstrap.netlify.app/components/carousel/ ?

Comment (kyletsang) [reply src/Carousel.tsx]: doh ignore.  my branch wasn't updated..  sorry!

strictmode and non strictmode works

**Comment by cjmaret** [comment]
this issue still exists for me

**Comment by deumolo** [comment]
Was this ever solved ?
