### PR TITLE
Fix placements

### LINKED ISSUE #5111: Tooltips with position auto are placed on top of the element
## Describe the bug

It seems as if tooltips that uses `placement="auto"` are no longer working since popperjs2 upgrade in react-overlays.

There seems to be other issues as well with placements of tooltips. Look at the linked example on the buttons and the headers. :(

## To Reproduce

1. Create a button
2. Wrap it in an overlaytrigger with placement auto
3. Tooltip is rendered inside the button

## Reproducible Example

Example: https://codesandbox.io/s/bold-chaum-4xhmr?file=/src/App.js

## Expected behavior

That tooltips works as in beta 17.

## Screenshots

v1.0.0
Screenshot 2020-04-14 at 11 50 29
Screenshot 2020-04-14 at 11 50 34

beta17
Screenshot 2020-04-14 at 11 50 47
Screenshot 2020-04-14 at 11 50 49

### PR DESCRIPTION
**Pull request by jquense**
closes #5111

### CODE REVIEW

File: src/Tooltip.tsx [hunk 1]
```diff
@@ -99,13 +99,19 @@ const Tooltip: Tooltip = React.forwardRef<HTMLDivElement, TooltipProps>(
...
         ref={ref}
         style={style}
         role="tooltip"
-        x-placement={placement}
-        className={classNames(className, bsPrefix, `bs-tooltip-${placement}`)}
+        x-placement={primaryPlacement}
+        className={classNames(
+          className,
+          bsPrefix,
+          `bs-tooltip-${primaryPlacement}`,
```
Comment (taion) [inline src/Tooltip.tsx:113]: **nitpick:** we shouldn't do `bs-tooltip-undefined` or whatever we'd get when `placement` is null, should we?

File: src/Popover.tsx [hunk 2]
```diff
@@ -94,16 +94,18 @@ const Popover: Popover = (React.forwardRef<HTMLDivElement, PopoverProps>(
...
         ref={ref}
         role="tooltip"
         style={style}
-        x-placement={placement}
+        x-placement={primaryPlacement}
         className={classNames(
           className,
           decoratedBsPrefix,
-          `bs-popover-${placement}`,
+          `bs-popover-${primaryPlacement}`,
```
Comment (jquense) [inline src/Popover.tsx:108]:
```suggestion
          primaryPlacement  && `bs-popover-${primaryPlacement}`,
```

File: src/Tooltip.tsx (hunk 1 above)
Comment (taion) [reply src/Tooltip.tsx:113]: this should be `primaryPlacement &&` as well
