### PR TITLE
[fixed] Tooltip accepts a style prop

### LINKED ISSUE #1027: Style passthroughs on Tooltips
We think a user should be able to supply a `style` prop to Tooltips, because this would be consistent with the behavior of most other components. Currently, any `style` prop passed into a tooltip will be ignored.

https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Tooltip.js#L72

Style is being defined and supplied with left and top attributes only. We would like to be able to provide other styles as a prop to Tooltips.

```
<Tooltip style={{opacity: 1}} />
```

Should render a tooltip with merged styles (`{opacity: 1, top: Xpx, left: Xpx}`).

Would you be open to a PR?

cc/ @gpleiss @stubbornella @matt-royal @ctaymor

### PR DESCRIPTION
**Pull request by kennyw12**
fixes #1027

### CODE REVIEW

File: src/Tooltip.js [hunk 1]
```diff
@@ -43,7 +43,11 @@ const Tooltip = React.createClass({
     /**
      * Title text
      */
-    title: React.PropTypes.node
+    title: React.PropTypes.node,
+    /**
+     * Style hash
+     */
+    style: React.PropTypes.object
```
Comment (taion) [inline src/Tooltip.js]: I'd actually rather not explicitly document this since it just adds to the clutter, but that's totally just personal preference on my part.

**Comment by taion** [comment]
LGTM. Need one more from @react-bootstrap/collaborators to sign off.

**Comment by dozoisch** [comment]
Yeah Looks good! 

Would it be worth mentioning that style top/left overrides positionTop and positionLeft ?

**Comment by taion** [comment]
@dozoisch We okay with cleaning up docs after merging this?

**Comment by dozoisch** [comment]
@taion I am! Alright merging, then!
