### PR TITLE
fix: Prevent Dropdown Flickering on 'mousedown' rootCloseEvent

### LINKED ISSUE #6712: Dropdown.Toggle does not work correctly when using mousedown as rootCloseEvent
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

This was already reported back in 2018 (https://github.com/react-bootstrap/react-bootstrap/issues/3196) and is still an issue.

Just create a dropdown with the `rootCloseEvent="mousedown"`. When tyring to close the dropdown with the toggle button the dropdown will flicker since it is hidden on mousedown but is being shown on onClick due to the logic in the toggle.

`mousedown` is in some circumstances essential to the functionality over the `click` rootCloseEvent.
For example I have a Drag&Drop Grabber to move the object where the dropdown lives. There will be no onClick event since I am dragging the item but I do want the dropdown to close when I drag the item.

```
<Dropdown>
    <Dropdown.Toggle variant="success" id="dropdown-basic">
        Dropdown Button
    </Dropdown.Toggle>

    <Dropdown.Menu rootCloseEvent="mousedown">
        <Dropdown.Item href="#/action-1">Action</Dropdown.Item>
        <Dropdown.Item href="#/action-2">Another action</Dropdown.Item>
        <Dropdown.Item href="#/action-3">Something else</Dropdown.Item>
    </Dropdown.Menu>
</Dropdown>
```

### Expected behavior

The toggle should support any valid `rootCloseEvent` as you would expect or the `mousedown` rootCloseEvent should be removed since its only supported for hiding and not showing.

### To Reproduce

_No response_

### Reproducible Example

https://codesandbox.io/s/xenodochial-frost-69cl6x

### Screenshots

_No response_

### What operating system(s) are you seeing the problem on?

_No response_

### What browser(s) are you seeing the problem on?

_No response_

### What version of React-Bootstrap are you using?

2.9.0

### What version of Bootstrap are you using?

5.3.2

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mvaibhav77**
Issue
Closes #6712 and #3196 

### Description
This pull request addresses the issue reported in #6712. When a dropdown is open with rootCloseEvent set to 'mousedown,' it currently exhibits flickering behavior when the toggle button is clicked. This issue arises due to the combination of hiding and showing the dropdown within the same click event.

### Changes Made
To resolve this issue, I've made the following changes:
Modified the handleToggle function to skip execution when the dropdown is open, and rootCloseEvent is set to 'mousedown,' and the toggle button is clicked. This change prevents the flickering behavior by allowing the dropdown to remain open in this specific scenario.

### Result
https://github.com/react-bootstrap/react-bootstrap/assets/100420038/4e68d2d1-8e26-4164-bbbb-cffc3bcd9747

### Additional Information
This change is made in response to the issue reported by @Fyers. We believe this modification improves the behavior of the dropdown component when rootCloseEvent is set to 'mousedown.'

I kindly request a review from the maintainers and the community to consider including this fix in the React Bootstrap project.

### CODE REVIEW

**Comment by mvaibhav77** [comment]
Hi @kyletsang, could you kindly review my pull request (PR) when you have a moment?

File: src/Dropdown.tsx [hunk 1]
```diff
@@ -147,6 +147,17 @@ const Dropdown: BsPrefixRefForwardingComponent<'div', DropdownProps> =
 
     const handleToggle = useEventCallback(
       (nextShow: boolean, meta: ToggleMetadata) => {
+        /** Checking if target of event is ToggleButton,
+         * if it is then nullify mousedown event
+         */
+        const isToggleButton = (
+          meta.originalEvent?.target as HTMLElement
+        )?.classList.contains('dropdown-toggle');
+
```
Comment (mvaibhav77) [inline src/Dropdown.tsx:156]: if event target is "toggleButton" and event is "mousedown" then skip handleToggle function

**Comment by kyletsang** [comment]
Could you add a test for this?

**Comment by mvaibhav77** [comment]
> Could you add a test for this?

Hey @kyletsang, added a test for the same.

**Comment by mvaibhav77** [comment]
@kyletsang, Can you review the PR once more? I would like to get this PR merged before Hacktoberfest ends.

**Review by kyletsang — APPROVED** [review]

**Comment by kyletsang** [comment]
Thanks
