### PR TITLE
fix(navbar): resolve lifecycle warning issue

### LINKED ISSUE #4240: Navbar Uses componentWillMount Still
## Describe the bug
I was getting a warnings after setting up some unit tests in my project. After digging in it looks like the Navbar component still uses componentWillMount. It looks like other components are being updated to use the hook form of uncontrollable (useUncontrollable). Are there plans and/or a timeline for Navbar to be updated to no longer depend on the legacy versions of these lifecycle hooks? It's not a pressing issue, just a bit of an eyesore!

## Screenshots

image

image

### PR DESCRIPTION
**Pull request by bpas247**
This migrates the Navbar component to be a function component, which should resolve the lifecycle deprecation warnings.

fixes #4240

### CODE REVIEW

File: src/Navbar.js [hunk 1]
```diff
@@ -122,103 +122,82 @@ const defaultProps = {
...
+  // "nulling" of the role if the user really doesn't want one
+  if (controlledProps.role === undefined && Component !== 'nav') {
+    controlledProps.role = 'navigation';
   }
-}
+  let expandClass = `${bsPrefix}-expand`;
+  if (typeof expand === 'string') expandClass = `${expandClass}-${expand}`;
+
+  return (
+    <NavbarContext.Provider value={{ handleToggle, bsPrefix, expanded }}>
```
Comment (jquense) [inline src/Navbar.js]: we should `useMemo` the `value` here, otherwise React will trigger an update of any Consumers of this every time Navbar renders, since the object will not `===` the last object.

**Comment by bpas247** [comment]
I'm not exactly sure why the [deploy preview failed](https://app.netlify.com/sites/react-bootstrap/deploys/5d54b7c437168e000c0bd374), but it should be ready for review now 🚀
