### PR TITLE
Don't incorrectly pass onSelect past TabContainer

### LINKED ISSUE #1822: Tab collapses on FormControl focus
In my application I have three `Tab` components inside of a `Tabs` component. Each `Tab` has a set of `FormControl` elements. I just upgraded to the latest react-bootstrap and with the previous implementation of the above with `Input` all worked fine.

Now, however, whenever a input field is clicked or otherwise given focus, the whole Tab collapses.
I'm not getting any errors or warnings in the console.

Here's a minimal and verifiable code that I tried on its own, which also produces the above issue:

    <Tabs activeKey={this.state.tabsKey} onSelect={this._handleSelect} animation={false} id="sub-task-tabs">
      <Tab eventKey={1} title="Extern länk">
        <FormGroup>
          <ControlLabel>Titel</ControlLabel>
          <FormControl type="text" onChange={this._subTaskInputChange0} value={this.state.subTaskInput0} />
        </FormGroup>
      </Tab>
    </Tabs>

Here's two screenshots I took.

_Before click on input field (Titel):_

img1

_After:_

img2

### PR DESCRIPTION
**Pull request by taion**
Fixes #1822

I don't have a test case here because I'm not sure I could write one without its just looking sorta dumb.

### CODE REVIEW

File: src/TabContainer.js [hunk 1]
```diff
@@ -64,25 +64,25 @@ let TabContainer = React.createClass({
     })
   },
 
-  getDefaultProps() {
-    return {
-      componentClass: 'div'
```
Comment (taion) [inline src/TabContainer.js]: This was not a prop on this component.

**Comment by taion** [comment]
@jquense Does this look okay to you?
