### PR TITLE
fix(types): add bootstrap sizes for Form.Label as column

### LINKED ISSUE #3481: Form.Label prop typings is missing xs, sm, md, lg, xl properties
One cannot specify `xs`, `sm`, `md`, `lg`, or `xl` properties on `Form.Label` like in this [example](https://react-bootstrap.github.io/components/forms/#forms-input-Plaintext).

```jsx
  <Form.Group as={Row} controlId="formPlaintextEmail">
    <Form.Label column sm="2">
      Email
    </Form.Label>
    <Col sm="10">
      <Form.Control plaintext readOnly defaultValue="email@example.com" />
    </Col>
  </Form.Group>
```

This is because they are missing from the typings in `FormLabel.d.ts`, which was clearly copied from `Feedback.d.ts`.

```typescript
import * as React from 'react';

import { BsPrefixComponent } from './helpers';

interface FeedbackProps {
  htmlFor?: string;
  column?: boolean;
  innerRef?: React.LegacyRef<this>;
  srOnly?: boolean;
}

declare class Feedback extends BsPrefixComponent<'label', FeedbackProps> {}

export default Feedback;
```

### PR DESCRIPTION
**Pull request by dalevfenton**
I'm not sure if just extending `FormLabelProps` with `ColProps` is the preferred way to solve this issue or if you would want something that actually enforces that the column size props are only valid when `column` is `true`.

I can make the typing stricter if that's preferred. It also seems like generally types aren't imported around and reused so if that's a problem I can copy them over completely from `Col.d.ts`

### CODE REVIEW

File: types/components/FormLabel.d.ts [hunk 1]
```diff
@@ -1,8 +1,9 @@
 import * as React from 'react';
 
 import { BsPrefixComponent } from './helpers';
+import { ColProps } from './Col';
 
-export interface FormLabelProps {
+export interface FormLabelProps extends ColProps {
```
Comment (jquense) [inline types/components/FormLabel.d.ts]: I wonder if the right way to do this is via a type Union, e.g. `FormLabel | FormLabelWithColProps` there `column` is `true` or `false` specifically (instead of `boolean`) to allow TS to differentiate

Comment (dalevfenton) [reply types/components/FormLabel.d.ts]: I started to do that, but didn't see that throughout the other typings so I wasn't sure if there was a preferred style. Let me write it up with the type Union.

**Comment by dalevfenton** [comment]
one thing to note is that since `FormLabelProps` is now a `type` instead of an `interface` if anyone is currently using that to extend their own interface it will break their interface declaration

**Comment by dalevfenton** [comment]
@jquense I think this should be good to go now.

**Comment by jquense** [comment]
thanks!
