### PR TITLE
fix(Modal): set display block always, fixes #3399

### LINKED ISSUE #3399: react-bootstrap 1.0.0-beta.3 disabling animation in modal not working
#### Version and browser:
react-bootstrap@^1.0.0-beta.3
Electron so chrome/chromium (v66)

#### Usage:
      <Modal animation={false} show={show} onHide={onHide}>
        <Modal.Header closeButton>
          <Modal.Title>
            Some header...
          </Modal.Title>
        </Modal.Header>
        <Modal.Body>
          Some body paragraphs...
        </Modal.Body>
        <Modal.Footer>
          Some buttons ...
        </Modal.Footer>
      </Modal>

#### Expected
Modal shown when `show` is set to `true` no matter `animation` is set to `true` or `false`

#### But
When `animation` is not set (default is `true`), modal is shown properly (btw, animation not so smooth); when `false`, screen becomes completely black without the modal.

#### Observation
By looking at developer tools, I see that the `div[role=dialog]` element which is the parent of the modal `div.modal-dialog` has style `display: none`.

### PR DESCRIPTION
**Pull request by kt3k**
We started setting `display: block` to div.modal at onEnter timing of Transition at Pull #3187. But when we set `animation={false}` to Modal, the Transition object is not created and therefore onEnter (=handleEnter) is not called. This causes empty modal when animation set `false` (I think this is the issue #3399 ). This PR tries to fix this behavior by setting the modal's display style to `block` always.

I think this doesn't break existing behavior because as @jquense says
> we don't allow modals to be in the DOM prior to showing 

the modal's dom element doesn't exist before rendering. So I think it's safe to set display always `block`.

### CODE REVIEW

File: src/Modal.js [hunk 1]
```diff
@@ -340,7 +338,7 @@ class Modal extends React.Component {
             onExiting,
             manager,
             ref: this.setModalRef,
-            style: { ...style, ...this.state.style },
+            style: { ...style, display: 'block', ...this.state.style },
```
Comment (taion) [inline src/Modal.js]: i think it'd be best to do this only when `animation` is disabled

Comment (kt3k) [reply src/Modal.js]: OK, I'll update.

**Comment by prakis** [comment]
I still see this issue, my module versions are
    "react-bootstrap": "1.0.0-beta.5",
    "bootstrap": "4.3.1",

Thank you

**Comment by kt3k** [comment]
@prakis This change was first included in `v1.0.0-beta.7`. You need to update to that version or above.

**Comment by prakis** [comment]
@kt3k Thank you. I am testing it.
When I set animation={false}  now the background-color is dark black(not the usual semi-transparent).
